image:
  repository: "ghga/purge-controller-service"

configPrefix: pcs

# Service parameters

# Service base path
apiBasePath: /pcs/
# Name of the database
mongodb:
  dbName: purge-controller

# This parameter is used as Kafka's group id
serviceName: pcs-rest

config:
  host: 0.0.0.0
  mongo_dsn: null
  db_name: pcs
  service_instance_id: rest.1
  token_hashes: []
  enable_opentelemetry: false
  otel_exporter_endpoint: "http://localhost:4318/"
  otel_exporter_protocol: "http/protobuf"

cmd: pcs run-rest

_topics:
  filesToDelete:
    # as producer
    topic:
      name: file_deletion_request_topic
      value: purges
    type:
      name: file_deletion_request_type
      value: file_deletion_requested
    kafkaUser:
      operations:
        - Write
