apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  annotations:
    configmap-hash: {{ include (print $.Template.BasePath "/configmap.yml") . | sha256sum }}
  labels:
    app: {{ .Release.Name }}
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        configmap-hash: {{ include (print $.Template.BasePath "/configmap.yml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        app: {{ .Release.Name }}
        version: staging
        sidecar.istio.io/inject: "true"
    spec:
      {{- include "ghga-common.image-pull-secrets" . | nindent 6 }}
      serviceAccountName: {{ .Release.Name }}
      shareProcessNamespace: {{ .Values.shareProcessNamespace }}
      containers:
      - image: "{{ .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        {{- include "ghga-common.command-args" (list "wps run-rest")  | nindent 8 }}
        name: {{ .Release.Name }}-rest
        securityContext:
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: "RuntimeDefault"
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        ports:
        - containerPort: {{ .Values.port }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.port }}
          initialDelaySeconds: 30
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: {{ .Values.port }}
          initialDelaySeconds: 30
          periodSeconds: 15
        volumeMounts:
        - name: config-rest
          mountPath: "/home/appuser/.{{ .Values.config_prefix }}.yaml"
          subPath: .{{ .Values.config_prefix }}.yaml
          readOnly: true
        {{- include "ghga-common.volume-mounts" . | nindent 8 }}
      - image: "{{ .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        {{- include "ghga-common.command-args" (list "wps consume-events")  | nindent 8 }}
        name: {{ .Release.Name }}-consumer
        securityContext:
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: "RuntimeDefault"
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        volumeMounts:
        - name: config-consumer
          mountPath: "/home/appuser/.{{ .Values.config_prefix }}.yaml"
          subPath: .{{ .Values.config_prefix }}.yaml
          readOnly: true
        {{- include "ghga-common.volume-mounts" . | nindent 8 }}
      volumes:
      - name: config-rest
        configMap:
          name: {{ .Release.Name }}
          items:
          - key: parameters-rest
            path: .{{ .Values.config_prefix }}.yaml
      - name: config-consumer
        configMap:
          name: {{ .Release.Name }}
          items:
          - key: parameters-consumer
            path: .{{ .Values.config_prefix }}.yaml
      {{- include "ghga-common.volumes" . | nindent 6 }}
      restartPolicy: Always
