apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-drs3-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: drs3
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80