apiVersion: v1
kind: Service
metadata:
  name: drs3
  labels:
    category: drs3
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: drs3