args: []
command: []
horizontalPodAutoscaler:
  enabled: false
  averageCpuUtilization: 75
  averageMemoryUtilization: 75
image:
  name: "ghga/encryption-key-store-service"
podAnnotations: {}
port: "8080"
resources:
  limits:
    cpu: "500m"
    memory: "256M"
  requests:
    cpu: "100m"
    memory: "64M"

config_prefix: ekss

ingress:
  enabled: false
  annotations: {}
  hostname: ""
  prefix: /
  tls:
    enabled: false
    secretName: ""

mapping:
  enabled: false
  hostname: ""
  prefix: /
  rewrite: null

parameters:
  default:
    api_root_path: /
    auto_reload: false
    cors_allow_credentials: false
    cors_allowed_headers: []
    cors_allowed_methods: []
    cors_allowed_origins: []
    docs_url: /docs
    host: 0.0.0.0
    log_level: info
    openapi_url: /openapi.json
    port: 8080
    server_private_key: <Please fill>
    server_public_key: <Please fill>
    service_name: encryption_key_store
    vault_url: http://vault:8200
    vault_verify: false
    vault_role_id: null
    vault_secret_id: null
    workers: 1

shareProcessNamespace: false
