image:
  repository: "ghga/encryption-key-store-service"

config_prefix: ekss

parameters:
  default:
    host: 0.0.0.0
    server_private_key: <Please fill>
    server_public_key: <Please fill>
    service_instance_id: 'ekss_1'
    vault_url: http://vault:8200
    vault_path: ekss

containers:
- name: rest
  type: "rest"
  cmd: ekss
  config:
    name: parameters
    key: parameters
