args: []
command: []
horizontalPodAutoscaler:
  enabled: false
  averageCpuUtilization: 75
  averageMemoryUtilization: 75
image:
  name: "ghga/encryption-key-store-service"
podAnnotations: {}
port: "8080"
resources:
  limits:
    cpu: "500m"
    memory: "256M"
  requests:
    cpu: "100m"
    memory: "64M"

config_prefix: ekss

mapping:
  enabled: false
  hostname: ""
  prefix: /
  rewrite: null

parameters:
  api_root_path: /
  auto_reload: false
  cors_allow_credentials: false
  cors_allowed_headers: []
  cors_allowed_methods: []
  cors_allowed_origins: []
  debug_vault: false
  docs_url: /docs
  host: 0.0.0.0
  log_level: info
  openapi_url: /openapi.json
  port: 8080
  server_private_key: <Please fill>
  server_public_key: <Please fill>
  service_name: encryption_key_store
  vault_host: http://vault
  vault_port: 8200
  vault_role_id: '**********'
  vault_secret_id: '**********'
  workers: 1

shareProcessNamespace: false
