exports:
  defaults:
    serviceaccount:
      create: true


    service:
      type: ClusterIP

      ports:
        - name: http
          protocol: TCP
          port: 8080
          targetPort: http

      sessionAffinity: None

      clusterIP: ""

      loadBalancerIP: ""

      loadBalancerSourceRanges: []

      externalTrafficPolicy: Cluster

      annotations: {}
