exports:
  defaults:
    global:
      imageRegistry: ""
      imagePullSecrets: []
      storageClass: ""
      topics: {}

    deployment:
      enabled: true
    
    job:
      enabled: false

    nameOverride: ""

    fullnameOverride: ""

    namespaceOverride: ""

    clusterDomain: cluster.local

    annotations: {}

    labels: {}

    commonLabels: {}

    commonAnnotations: {}

    image:
      registry: docker.io
      repository: ""
      tag: ""
      digest: ""
      pullPolicy: null
      pullSecrets: []

    replicaCount: 1

    revisionHistoryLimit: 1

    shareProcessNamespace: false

    podSecurityContext:
      enabled: false
      fsGroup: 0

    initContainers: []

    hostAliases: []

    podLabels: {}

    podAnnotations: {}

    podAffinityPreset: ""

    podAntiAffinityPreset: soft

    nodeAffinityPreset:
      type: ""
      key: ""
      values: []

    affinity: {}

    nodeSelector: {}

    tolerations: []

    topologySpreadConstraints: []

    priorityClassName: ""

    schedulerName: ""

    terminationGracePeriodSeconds: ""

    updateStrategy:
      type: RollingUpdate

    podRestartPolicy: Always

    containers:
      - config: {}
        name: default
        cmd: /bin/sh
        type: rest

    ports:
      - name: http
        containerPort: 8080
        protocol: TCP

    livenessProbe:
      enabled: true
      tcpSocket:
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 15

    readinessProbe:
      enabled: true
      tcpSocket:
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 15

    startupProbe:
      enabled: false

    containerSecurityContext:
      enabled: true
      runAsUser: 1000
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: "RuntimeDefault"
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      allowPrivilegeEscalation: false

    lifecycleHooks: {}

    resources:
      limits:
        cpu: "1500m"
        memory: "2048M"
      requests:
        cpu: "1000m"
        memory: "1024M"

    extraVolumes: []

    extraVolumeMounts: []

    sidecars: []

    envVars: null

    envVarsConfigMap: ""

    envVarsSecret: ""

    service:
      type: ClusterIP
      ports:
        - name: http
          protocol: TCP
          port: 8080
          targetPort: http

    serviceAccount:
      create: true

    autoscaling:
      enabled: false
      minReplicas: 3
      maxReplicas: 5
      targetCPU: 80
      targetMemory: 80
      metrics: []

    ingress:
      enabled: false

    mapping:
      enabled: false
      port: 8080
      ambassador_id: default
      rewrite: /
      hostname: ""
      prefix: ""
      timeout_ms: 3000

    topicPrefix: ""
    topics: {}
    kafkaTopicsParameters: true

    kafkaUser:
      enabled: false
      clusterName: kafka
      clusterNamespace: strimzi
      caCertSecretName: kafka-cluster-ca-cert

    dbName: ""
    apiBasePath: ""
    serviceName: ""
    serviceInstanceId: ""
    serviceNameConsumer: ""
    serviceInstanceIdConsumer: ""
    parameters:
      default: {}
      rest: {}
      consumer: {}

    configPrefix: ""
    # This value is replaced in templated secrets with the actual config prefix before starting the service
    configPrefixPlaceholder: "%%CONFIG_PREFIX_PLACEHOLDER%%"

    enableServiceLinks: true

    vaultAgent:
      enabled: false
      authPath: kubernetes
      role: service-role
      secrets:
        mongodb:
          secretPath: database/creds/my-role
          pgrepPattern: python
          connectionString: "mongodb://{{username}}:{{password}}@mongodb:27017/admin"
        service:
          secretPath: operational-secrets/data/unique/apps/archive/service
          pgrepPattern: python
