exports:
  defaults:
    serviceaccount:
      create: true
    
    # Ports which should be exposed in pod
    ports:
      - name: http
        containerPort: 8080
        protocol: TCP

    service:
      type: ClusterIP

      ports:
        - name: http
          protocol: TCP
          port: 8080
          targetPort: http

      sessionAffinity: None

      clusterIP: ""

      loadBalancerIP: ""

      loadBalancerSourceRanges: []

      externalTrafficPolicy: Cluster

      annotations: {}
