image:
  repository: "ghga/access-request-service"

configPrefix: ars

# Service parameters

# Service base path
apiBasePath: /ars/
# Name of the database
mongodb:
  dbName: access-request
# This parameter is used as Kafka's group id
serviceName: ars-rest
# This parameter specifies the client id in Kafka
serviceInstanceId: ars-rest-1

# Those values are directly injected into the service's configuration
parameters:
  default:
    auth_key: '{}'
    mongo_dsn: null
    download_access_url: http://claims-repository:8080/download-access
    host: "0.0.0.0"

containers:
- name: rest
  type: "rest"
  cmd: ars
  config:
    name: parameters
    key: parameters

_consumer_group:

_topics:
  fileRegisteredEvent:
    # as producer
    topic:
      name: access_request_topic
      value: access-requests
    types:
    - name: access_request_created_type
      value: access_request_created
    - name: access_request_allowed_type
      value: access_request_allowed
    - name: access_request_denied_type
      value: access_request_denied
    kafkaUser:
      operations:
        - Write
        - Create
