image:
  repository: "ghga/auth-km-jobs"

configPrefix: auth_km_jobs

cronjob:
  enabled: true

cronSchedule: "0 0 1 1 0"

containers:
- name: default
  type: default
  cmd: "run refresh-int-keys"
  config: {}
# internal: run refresh-int-keys
# external: run refresh-ext-keys
# wps: run refresh-wps-keys

envVars:
  - name: AUTH_KM_JOBS_TOKEN
    value:  ""
  - name: AUTH_KM_JOBS_VAULT_ADDR
    value: https://hashicorp-vault.vault:8200
  - name: AUTH_KM_JOBS_VAULT_NAMESPACE
    value: vault
  - name: AUTH_KM_JOBS_VAULT_ROLE
    value: auth-km-jobs-role
