apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: kafka-certs
      mountPath: "/certs"
      readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: dotfile-secret
        
