apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metadata-catalog
  name: metadata-catalog
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: metadata-catalog
  template:
    metadata:
      annotations:
      labels:
        app: metadata-catalog
        sidecar.istio.io/inject: "true"
        version: staging
    spec:
      containers:
        - env:
            - name: METADATA_CATALOG_HOST
              value: 0.0.0.0
            - name: METADATA_CATALOG_PORT
              value: "8080"
            - name: METADATA_CATALOG_SVC_SEARCH_URL
              value: /api/search
            - name: METADATA_CATALOG_SVC_REPOSITORY_URL
              value: /api/repository
          image: ghga/metadata-catalog:0.0.0-59-031dafb-main
          name: metadata-catalog
          securityContext:
            runAsUser: 1000
            capabilities:
              drop:
                - all
      #      readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: "RuntimeDefault"
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 240
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 240
            periodSeconds: 15 
          resources:
            limits:
              cpu: 1500m
              memory: 2048M
            requests:
              cpu: 1000m
              memory: 1024M 