args: []
command: []
horizontalPodAutoscaler:
  enabled: false
  averageCpuUtilization: 75
  averageMemoryUtilization: 75
image:
  name: "ghga/notification-service"
  tag: "0.1.2"
podAnnotations: {}
port: "8080"
resources:
  limits:
    cpu: "500m"
    memory: "256M"
  requests:
    cpu: "100m"
    memory: "64M"

config_prefix: ifrs

mapping:
  enabled: false
  hostname: ""
  prefix: /
  rewrite: null

parameters:
  from_address: test@test.com
  html_email_template: >-
    <!DOCTYPE html>
    <html>
    <head></head>
    <body style="color: #00393f;padding:12px;">
    <h2>Dear $recipient_name,</h2>
    <p>$plaintext_body</p>
    <p>Warm regards,</p>
    <h3>The GHGA Team</h3>
    </body>
    </html>
  kafka_servers:
  - kafka:9092
  login_password: test
  login_user: test@test.com
  notification_event_topic: notifications
  notification_event_type: notification
  plaintext_email_template: |
    Dear $recipient_name,

    $plaintext_body

    Warm regards,
    The GHGA Team
  service_instance_id: 'ns_1'
  service_name: ns
  smtp_host: 127.0.0.1
  smtp_port: 587
  use_starttls: false

shareProcessNamespace: false
