horizontalPodAutoscaler:
  enabled: false

image:
  repository: "ghga/notification-orchestration-service"

config_prefix: nos

parameters:
  default:
    access_request_allowed_event_type: access_request_allowed
    access_request_created_event_type: access_request_created
    access_request_denied_event_type: access_request_denied
    access_request_events_topic: access_requests
    central_data_stewardship_email: ""
    db_name: nos
    iva_state_changed_event_topic: ivas
    iva_state_changed_event_type: iva_state_changed
    notification_event_topic: notifications
    notification_event_type: notification
    second_factor_recreated_event_topic: auth
    second_factor_recreated_event_type: second_factor_recreated
    service_instance_id: 'consumer.1'
    service_name: nos
    user_events_topic: users
    file_registered_event_topic: internal_registrations
    file_registered_event_type: internal_file_registered

kafkaSecrets:
  enabled: false

containers:
- name: rest
  type: "rest"
  cmd: nos
  config:
    name: parameters
    key: parameters
