image:
  repository: "ghga/notification-orchestration-service"

config_prefix: nos

parameters:
  default:
    central_data_stewardship_email: ""
    helpdesk_email: ""
    db_name: nos
    service_instance_id: 'consumer.1'

containers:
- name: consumer
  type: consumer
  cmd: nos
  config:
    name: parameters
    key: parameters

topics:
  accessRequestEvents:
    topic:
      name: access_request_events_topic
      value: access-requests
    types:
    - name: access_request_created_event_type
      value: access_request_created
    - name: access_request_allowed_event_type
      value: access_request_allowed
    - name: access_request_denied_event_type
      value: access_request_denied
  ivaStateChangeEvent:
    topic:
      name: iva_state_changed_event_topic
      value: ivas
    types:
    - name: iva_state_changed_event_type
      value: iva_state_changed
  notificationEvent:
    topic:
      name: notification_event_topic
      value: notifications
    types:
    - name: notification_event_type
      value: notification
  secondFactorRecreatedEvent:
    topic:
      name: second_factor_recreated_event_topic
      value: auth
    types:
    - name: second_factor_recreated_event_type
      value: second_factor_recreated
  fileRegisteredEvent:
    topic:
      name: file_registered_event_topic
      value: internal-registrations
    types:
    - name: file_registered_event_type
      value: internal_file_registered
  userEvents:
    topic:
      name: user_events_topic
      value: users
