horizontalPodAutoscaler:
  enabled: false

image:
  repository: "ghga/internal-file-registry-service"

config_prefix: ifrs

parameters:
  default:
    db_connection_str: null
    db_name: ifrs
    file_deleted_event_topic: internal_registrations
    file_deleted_event_type: internal_file_deleted
    file_registered_event_topic: internal_registrations
    file_registered_event_type: internal_file_registered
    file_staged_event_topic: internal_registrations
    file_staged_event_type: internal_file_staged
    files_to_delete_topic: purges
    files_to_register_topic: interrogations
    files_to_stage_topic: downloads
    service_instance_id: "consumer.1"
    service_name: internal_file_registry

    object_storages: {}
    #   test:
    #     bucket: permanent
    #     credentials:
    #       aws_config_ini: null
    #       s3_endpoint_url: null
    #       s3_access_key_id: null
    #       s3_secret_access_key: null
    #       s3_session_token: null

kafkaSecrets:
  enabled: false

containers:
- name: consumer
  type: "consumer"
  cmd: ifrs
  config:
    name: parameters
    key: parameters
