args: []
command: []
horizontalPodAutoscaler:
  enabled: false
  averageCpuUtilization: 75
  averageMemoryUtilization: 75
image:
  name: "ghga/internal-file-registry-service"
podAnnotations: {}
resources:
  limits:
    cpu: "500m"
    memory: "256M"
  requests:
    cpu: "100m"
    memory: "64M"

config_prefix: ifrs

parameters:
  default:
    db_connection_str: null
    db_name: ifrs
    file_deleted_event_topic: internal_registrations
    file_deleted_event_type: internal_file_deleted
    file_registered_event_topic: internal_registrations
    file_registered_event_type: internal_file_registered
    file_staged_event_topic: internal_registrations
    file_staged_event_type: internal_file_staged
    files_to_delete_topic: purges
    files_to_delete_type: files_to_delete
    files_to_register_topic: interrogations
    files_to_register_type: validation_success
    files_to_stage_topic: downloads
    files_to_stage_type: unstaged_drs_object_requested
    kafka_servers: []
    kafka_security_protocol: PLAINTEXT
    kafka_ssl_cafile: null
    kafka_ssl_certfile: null
    kafka_ssl_keyfile: null
    kafka_ssl_password: null
    service_instance_id: "consumer.1"
    service_name: internal_file_registry
    object_storages:
      test:
        bucket: permanent
        credentials:
          aws_config_ini: null
          s3_access_key_id: null
          s3_endpoint_url: null
          s3_secret_access_key: null
          s3_session_token: null

shareProcessNamespace: false
kafkaSecrets:
  enabled: false

imagePullSecretName: []
