image:
  repository: "ghga/internal-file-registry-service"

configPrefix: ifrs

# Service parameters

# Name of the database
dbName: internal-file-registry
# This parameter is used as Kafka's group id
serviceName: ifrs
# This parameter specifies the client id in Kafka
serviceInstanceId: ifrs-1

parameters:
  default:
    db_connection_str: null
    object_storages: {}
    db_version_collection: ifrsDbVersions
    migration_wait_sec: 10

containers:
- name: consumer
  type: "consumer"
  cmd: ifrs
  config:
    name: parameters
    key: parameters

topics:
  fileDeletedEvent:
    topic:
      name: file_deleted_event_topic
      value: internal-registrations
    types:
      - name: file_deleted_event_type
        value: internal_file_deleted
  fileRegisteredEvent:
    topic:
      name: file_registered_event_topic
      value: internal-registrations
    types:
      - name: file_registered_event_type
        value: internal_file_registered
  fileStagedEvent:
    topic:
      name: file_staged_event_topic
      value: internal-registrations
    types:
      - name: file_staged_event_type
        value: internal_file_staged
  filesToDelete:
    topic:
      name: files_to_delete_topic
      value: purges
  filesToRegister:
    topic:
      name: files_to_register_topic
      value: interrogations
  filesToStage:
    topic:
      name: files_to_stage_topic
      value: downloads
