image:
  repository: "ghga/internal-file-registry-service"

config_prefix: ifrs

parameters:
  default:
    db_connection_str: null
    db_name: ifrs
    service_instance_id: "consumer.1"
    object_storages: {}

containers:
- name: consumer
  type: "consumer"
  cmd: ifrs
  config:
    name: parameters
    key: parameters

topics:
  fileDeletedEvent:
    topic:
      name: file_deleted_event_topic
      value: internal-registrations
    types:
      - name: file_deleted_event_type
        value: internal_file_deleted
  fileRegisteredEvent:
    topic:
      name: file_registered_event_topic
      value: internal-registrations
    types:
      - name: file_registered_event_type
        value: internal_file_registered
  fileStagedEvent:
    topic:
      name: file_staged_event_topic
      value: internal-registrations
    types:
      - name: file_staged_event_type
        value: internal_file_staged
  filesToDelete:
    topic:
      name: files_to_delete_topic
      value: purges
  filesToRegister:
    topic:
      name: files_to_register_topic
      value: interrogations
  filesToStage:
    topic:
      name: files_to_stage_topic
      value: downloads
