image:
  repository: "ghga/notification-service"

configPrefix: ns

# Service parameters

# Name of the database
mongodb:
  dbName: notification
# This parameter is used as Kafka's group id
serviceName: ns-consumer
# This parameter specifies the client id in Kafka
serviceInstanceId: ns-consumer-1
# This parameter is used as Kafka's group id
serviceNameConsumer: ns-consumer
# This parameter specifies the client id in Kafka
serviceInstanceIdConsumer: ns-consumer-1

parameters:
  default:
    mongo_dsn: null
    from_address: test@test.com
    html_email_template: >-
      <!DOCTYPE html>
      <html>
      <head></head>
      <body style="color: #00393f;padding:12px;">
      <h2>Dear $recipient_name,</h2>
      <p>$plaintext_body</p>
      <p>Warm regards,</p>
      <h3>The GHGA Team</h3>
      </body>
      </html>
    smtp_auth: null
    plaintext_email_template: |
      Dear $recipient_name,

      $plaintext_body

      Warm regards,
      The GHGA Team
    smtp_host: 127.0.0.1
    smtp_port: 587
    use_starttls: false
    kafka_enable_dlq: true

containers:
- name: consumer
  type: "consumer"
  cmd: ns
  config:
    name: parameters
    key: parameters

_consumer_group:

_topics:
  notificationEvent:
    topic:
      name: notification_topic
      value: notifications
    types:
      - name: notification_type
        value: notification
  # as producer
  deadLetterQueue:
    topic:
      name: kafka_dlq_topic
      value: dlq
    kafkaUser:
      operations:
        - Write
        - Create
  # as consumer
  deadLetterQueueRetry:
    topic:
      name: null
      value: retry
    kafkaUser:
      operations:
        - Read
        - Create
