image:
  repository: "ghga/internal-file-registry-service"

configPrefix: ifrs

# Service parameters

# Name of the database
mongodb:
  dbName: internal-file-registry
# This parameter is used as Kafka's group id
serviceName: ifrs
# This parameter specifies the client id in Kafka
serviceInstanceId: ifrs-1

parameters:
  default:
    mongo_dsn: null
    object_storages: {}
    kafka_enable_dlq: true

containers:
- name: consumer
  type: "consumer"
  cmd: ifrs consume-events
  config:
    name: parameters
    key: parameters

topics:
  fileDeletedEvent:
    # as producer
    topic:
      name: file_deleted_topic
      value: internal-registrations
    types:
      - name: file_deleted_type
        value: internal_file_deleted
  fileRegisteredEvent:
    # as producer
    topic:
      name: file_internally_registered_topic
      value: internal-registrations
    types:
      - name: file_internally_registered_type
        value: internal_file_registered
  fileStagedEvent:
    # as producer
    topic:
      name: file_staged_topic
      value: staged-files
    types:
      - name: file_staged_type
        value: internal_file_staged
  filesToDelete:
    # as consumer
    topic:
      name: file_deletion_request_topic
      value: purges
    type:
      name: file_deletion_request_type
      value: file_deletion_requested
  filesToRegister:
    # as consumer
    topic:
      name: file_interrogations_topic
      value: interrogations
    type:
      name: interrogation_success_type
      value: file_interrogation_success
  filesToStage:
    # as consumer
    topic:
      name: files_to_stage_topic
      value: staging-requests
    type:
      name: files_to_stage_type
      value: file_staging_requested
  deadLetterQueue:
    topic:
      name: kafka_dlq_topic
      value: dlq