image:
  repository: "ghga/internal-file-registry-service"

configPrefix: ifrs

# Service parameters

# Name of the database
mongodb:
  dbName: internal-file-registry
# This parameter is used as Kafka's group id
serviceName: ifrs

config:
  mongo_dsn: null
  object_storages: {}
  kafka_enable_dlq: true
  enable_opentelemetry: false
  otel_exporter_endpoint: "http://localhost:4318/"
  otel_exporter_protocol: "http/protobuf"

cmd: ifrs consume-events

_topics:
  fileDeletedEvent:
    # as producer
    topic:
      name: file_deleted_topic
      value: internal-registrations
    types:
      - name: file_deleted_type
        value: internal_file_deleted
    kafkaUser:
      operations:
        - Write
  fileRegisteredEvent:
    # as producer
    topic:
      name: file_internally_registered_topic
      value: internal-registrations
    types:
      - name: file_internally_registered_type
        value: internal_file_registered
    kafkaUser:
      operations:
        - Write
  fileStagedEvent:
    # as producer
    topic:
      name: file_staged_topic
      value: staged-files
    types:
      - name: file_staged_type
        value: internal_file_staged
    kafkaUser:
      operations:
        - Write
  filesToDelete:
    # as consumer
    topic:
      name: file_deletion_request_topic
      value: purges
    type:
      name: file_deletion_request_type
      value: file_deletion_requested
    kafkaUser:
      operations:
        - Read
  filesToRegister:
    # as consumer
    topic:
      name: file_interrogations_topic
      value: interrogations
    type:
      name: interrogation_success_type
      value: file_interrogation_success
    kafkaUser:
      operations:
        - Read
  filesToStage:
    # as consumer
    topic:
      name: files_to_stage_topic
      value: staging-requests
    type:
      name: files_to_stage_type
      value: file_staging_requested
    kafkaUser:
      operations:
        - Read
  # as producer
  deadLetterQueue:
    topic:
      name: kafka_dlq_topic
      value: dlq
    kafkaUser:
      operations:
        - Write
  # as consumer
  deadLetterQueueRetry:
    topic:
      name: null
      value: retry
    kafkaUser:
      operations:
        - Read
