image:
  repository: "ghga/auth-service"

configPrefix: auth_service

# Service parameters

# Service base path
apiBasePath: /auth-ext/
# Name of the database
mongodb:
  dbName: auth-service
# This parameter is used as Kafka's group id
serviceName: auth-adapter-rest
# This parameter specifies the client id in Kafka
serviceInstanceId: auth-adapter
# This parameter is used as Kafka's group id
serviceNameConsumer: auth-consumer
# This parameter specifies the client id in Kafka
serviceInstanceIdConsumer: auth-consumer-1

parameters:
  default:
    db_connection_str: null
    host: 0.0.0.0

authService:
  emissary:
    enabled: false
    name: authentication

containers:
- name: rest
  type: "rest"
  cmd: auth-service
  config:
    name: parameters
    key: parameters

topics:
  authEvents:
    topic:
      name: auth_events_topic
      value: auth
    types:
    - name: second_factor_recreated_event_type
      value: second_factor_recreated
  ivaEvents:
    topic:
      name: iva_events_topic
      value: ivas
    types:
    - name: iva_state_changed_event_type
      value: iva_state_changed
  datasetDeletionEvent:
    topic:
      name: dataset_deletion_event_topic
      value: metadata-datasets
    types:
    - name: dataset_deletion_event_type
      value: dataset_deleted
  userEvents:
    topic:
      name: user_events_topic
      value: users
