image:
  repository: "ghga/auth-service"

configPrefix: auth_service

# Service parameters

# Service base path
apiBasePath: /auth-ext/
# Name of the database
mongodb:
  dbName: auth-servicex§
# This parameter is used as Kafka's group id
serviceName: auth-consumer

config:
  mongo_dsn: null
  host: 0.0.0.0
  enable_opentelemetry: false
  db_version_collection: "authDbVersions"
  migration_wait_sec: 10

authService:
  emissary:
    enabled: false
    name: authentication

cmd: auth-service

_topics:
  authEvents:
    # as producer
    topic:
      name: auth_topic
      value: auth
    types:
    - name: second_factor_recreated_type
      value: second_factor_recreated
    kafkaUser:
      operations:
        - Write
  ivaEvents:
    # as producer
    topic:
      name: iva_state_changed_topic
      value: ivas
    types:
    - name: iva_state_changed_type
      value: iva_state_changed
    kafkaUser:
      operations:
        - Write
  datasetChangeEvent:
    # as consumer
    topic:
      name: dataset_change_topic
      value: metadata-datasets
    types:
    - name: dataset_deletion_type
      value: dataset_deleted
    - name: dataset_upsertion_type
      value: dataset_created
    kafkaUser:
      operations:
        - Read
  userEvents:
    # as producer
    topic:
      name: user_topic
      value: users
    kafkaUser:
      operations:
        - Write
