image:
  repository: "ghga/auth-service"

configPrefix: auth_service

# Service parameters

# Service base path
apiBasePath: /auth-ext/
# Name of the database
mongodb:
  dbName: auth-service
# This parameter is used as Kafka's group id
serviceName: auth-adapter-rest
# This parameter specifies the client id in Kafka
serviceInstanceId: auth-adapter
# This parameter is used as Kafka's group id
serviceNameConsumer: auth-consumer
# This parameter specifies the client id in Kafka
serviceInstanceIdConsumer: auth-consumer-1

parameters:
  default:
    mongo_dsn: null
    host: 0.0.0.0

authService:
  emissary:
    enabled: false
    name: authentication

containers:
- name: rest
  type: "rest"
  cmd: auth-service
  config:
    name: parameters
    key: parameters

_topics:
  authEvents:
    # as producer
    topic:
      name: auth_topic
      value: auth
    types:
    - name: second_factor_recreated_type
      value: second_factor_recreated
    kafkaUser:
      operations:
        - Write
  ivaEvents:
    # as producer
    topic:
      name: iva_state_changed_topic
      value: ivas
    types:
    - name: iva_state_changed_type
      value: iva_state_changed
    kafkaUser:
      operations:
        - Write
  datasetChangeEvent:
    # as consumer
    topic:
      name: dataset_change_topic
      value: metadata-datasets
    types:
    - name: dataset_deletion_type
      value: dataset_deleted
    - name: dataset_upsertion_type
      value: dataset_created
    kafkaUser:
      operations:
        - Read
  userEvents:
    # as producer
    topic:
      name: user_topic
      value: users
    kafkaUser:
      operations:
        - Write
