catalogHost: "0.0.0.0"
catalogPort: "8080"
svcRepositoryUrl: "/api/repository"
svcSearchUrl: "/api/search"
resources:
  limits:
    cpu: "1500m"
    memory: "2048M"
  requests:
    cpu: "1000m"
    memory: "1024M"