image:
  repository: "ghga/dataset-information-service"

config_prefix: dins

# Service parameters

# Service base path 
apiBasePath: /dins/
# Name of the database
dbName: dataset-information
# This parameter is used as Kafka's group id
serviceName: dins-rest
# This parameter specifies the client id in Kafka
serviceInstanceId: dins-rest-1
# This parameter is used as Kafka's group id
serviceNameConsumer: dins-consumer
# This parameter specifies the client id in Kafka
serviceInstanceIdConsumer: dins-consumer-1

# Those values are directly injected into the service's configuration
parameters:
  default:
    host: 0.0.0.0
    db_connection_str: null

containers:
- name: rest
  type: "rest"
  cmd: dins run-rest
  config:
    name: parameters-rest
    key: parameters-rest
- name: consumer
  type: "consumer"
  cmd: dins consume-events
  config:
    name: parameters-consumer
    key: parameters-consumer


topics:

  fileRegisteredEvent:
    topic:
      name: file_registered_event_topic
      value: internal-registrations
    types:
      - name: file_registered_event_type
        value: internal_file_registered
  filesToDelete:
    topic:
      name: files_to_delete_topic
      value: purges
  datasetUpsertionEvent:
    topic:
      name: dataset_event_topic
      value: metadata-datasets
    types:
      - name: dataset_upsertion_event_type
        value: dataset_created
  datasetDeletionEvent:
    topic:
      name: dataset_event_topic
      value: metadata-datasets
    types:
      - name: dataset_deletion_event_type
        value: dataset_deleted
