image:
  repository: "ghga/file-ingest-service"

config_prefix: fis

parameters:
  default:
    host: 0.0.0.0
    private_key: ""
    vault_url: http://vault:8200
    vault_path: ekss
    db_connection_str: null
    db_name: fis
    service_instance_id: rest.1
    token_hashes: []

containers:
- name: rest
  type: "rest"
  cmd: fis run-rest
  config:
    name: parameters
    key: parameters


topics:

  fileUploadValidationSuccess:
    topic:
      name: file_upload_validation_success_topic
      value: interrogations
