args: []
command: []
horizontalPodAutoscaler:
  enabled: false
  averageCpuUtilization: 75
  averageMemoryUtilization: 75
image:
  name: "ghga/file-ingest-service"
podAnnotations: {}
port: "8080"
resources:
  limits:
    cpu: "500m"
    memory: "256M"
  requests:
    cpu: "100m"
    memory: "64M"

config_prefix: fis

ingress:
  enabled: false
  annotations: {}
  hostname: ""
  prefix: /
  tls:
    enabled: false
    secretName: ""

mapping:
  enabled: false
  hostname: ""
  prefix: /
  rewrite: null
  ambassador_id: null
  timeout_ms: null

parameters:
  default:
    api_root_path: ""
    auto_reload: false
    cors_allow_credentials: false
    cors_allowed_headers: []
    cors_allowed_methods: []
    cors_allowed_origins: []
    docs_url: /docs
    host: 0.0.0.0
    openapi_url: /openapi.json
    port: 8080
    private_key: ""
    file_upload_validation_success_topic: interrogations
    file_validations_collection: file-validations
    db_connection_str: null
    db_name: fis
    service_instance_id: rest.1
    service_name: fis
    source_bucket_id: staging
    token_hashes: []
    vault_url: http://vault:8200
    vault_verify: false
    vault_role_id: null
    vault_secret_id: null
    vault_path: ekss
    vault_kube_role: null
    workers: 1
    selected_storage_alias: staging

shareProcessNamespace: false
kafkaSecrets:
  enabled: false

# Used to add image pull secrets to deployment
# imagePullSecretNames:
#  - name: dockerhub
#  - name: ex
imagePullSecretNames: []

# Add extra labels to the service pod
# podExtraLabels:
#   my-label: my-value
