image:
  repository: "ghga/file-ingest-service"

configPrefix: fis

# Service parameters

# Service base path
apiBasePath: /fis/
# Name of the database
dbName: file-ingest
# This parameter is used as Kafka's group id
serviceName: fis-rest
# This parameter specifies the client id in Kafka
serviceInstanceId: fis-rest-1

parameters:
  default:
    host: 0.0.0.0
    private_key: ""
    vault_url: http://vault:8200
    vault_path: ekss
    db_connection_str: null
    token_hashes: []

containers:
- name: rest
  type: "rest"
  cmd: fis run-rest
  config:
    name: parameters
    key: parameters


topics:

  fileUploadValidationSuccess:
    topic:
      name: file_upload_validation_success_topic
      value: interrogations
