image:
  repository: ghga/devops-remotebackup
  pullPolicy: IfNotPresent

schedule: "0 3 * * *"

configPrefix: config

containers:
- name: default
  type: default
  cmd: "remotebackup backup"
  config:
    name: config

vaultAgent:
  enabled: true
  secrets:
    mongodb:
      enabled: true
