image:
  repository: ghga/devops-remotebackup
  pullPolicy: IfNotPresent

cronSchedule: "0 3 * * *"

configPrefix: ""

containers:
- name: default
  type: default
  cmd: "remotebackup backup"
  config:
    name: config
    fileName: config.yaml

vaultAgent:
  enabled: true
  secrets:
    mongodb:
      enabled: true
