image:
  repository: ghga/devops-remotebackup
  pullPolicy: IfNotPresent

schedule: "0 3 * * *"

configPrefix: ""

vaultAgent:
  secrets:
    mongodb:
      parameterName: DATABASE__MONGODB__SOURCE_CONNECTION_STR

containers:
- name: default
  type: default
  cmd: remotebackup backup
  config:
    name: config
    fileName: config.yaml
