apiVersion: v1
kind: Service
metadata:
  labels:
    app: metadata-search-service
  name: metadata-search-service
spec:
  type: ClusterIP
  ports:
  - name: http-web
    port: 8080
    targetPort: 8080
  selector:
    app: metadata-search-service