podAnnotations: {}
command: []
args: []
horizontalPodAutoscaler:
  enabled: false
  averageCpuUtilization: 75
  averageMemoryUtilization: 75
image:
  name: "ghga/download-controller-service"
  tag: "0.6.0"
port: "8080"
resources:
  limits:
    cpu: 1500m
    memory: 2048M
  requests:
    cpu: 100m
    memory: 256M

parameters:
  api_root_path: ""
  api_route: ""
  auto_reload: true
  aws_config_ini: null
  cors_allow_credentials: false
  cors_allowed_headers: []
  cors_allowed_methods: []
  cors_allowed_origins: []
  db_print_logs: false
  docs_url: /docs
  host: 0.0.0.0
  log_level: info
  openapi_url: /openapi.json
  port: 8080
  s3_session_token: null
  service_name: drs3
  topic_name_drs_object_registered: drs-object-registered
  topic_name_file_registered: file-internally-registered
  topic_name_file_staged: file_staged_for_download
  topic_name_stage_request: non_staged_file_requested
  workers: 1
