apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  parameters: |
    {{- if .Values.parameters.default }}
    {{- toYaml .Values.parameters.default | nindent 4 }}
    {{- else }}
    {{- toYaml .Values.parameters | nindent 4 }}
    {{- end }}
