apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "remotebackup.fullname" . }}
  labels:
    {{- include "remotebackup.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.env_vars | nindent 4 }}
