apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "remotebackup.fullname" . }}
  labels:
    {{- include "remotebackup.labels" . | nindent 4 }}
  annotations:
    configmap-hash: {{ include (print $.Template.BasePath "/configmap.yml") . | sha256sum }} 
spec:
  schedule: {{ .Values.schedule }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            configmap-hash: {{ include (print $.Template.BasePath "/configmap.yml") . | sha256sum }}
            {{- with .Values.podAnnotations }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          {{- if .Values.serviceAccount.enabled }}
          serviceAccountName: {{ .Values.serviceAccount.name }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              imagePullPolicy: {{ .Values.image.pullPolicy }} 
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              {{- include "ghga-common.command-args" (list .Values.runCommands )  | nindent 14 }}
              envFrom:
                - configMapRef:
                    name: {{ include "remotebackup.fullname" . }}
              {{- with .Values.resources }}
              resources:
              {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.securityContext }}
              securityContext:
              {{- toYaml . | nindent 16 }}
              {{- end }}
              volumeMounts:
              - name: config-yaml
                mountPath: "/home/appuser/config.yaml"
                subPath: config.yaml
                readOnly: true
          restartPolicy: {{ .Values.restartPolicy }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml .Values.imagePullSecrets | nindent 10 }}
          {{- end }}
          volumes:
          - name: config-yaml
            configMap:
              name: {{ include "remotebackup.fullname" . }}-config-yaml
              items:
              - key: config.yaml
                path: config.yaml