{{ if .Values.mapping.enabled }}
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: {{ .Release.Name }}-loadartifacts
spec:
  ambassador_id: {{ .Values.mapping.ambassador_id }}
  service: "{{ .Release.Name }}-svc:{{ .Values.mapping.port }}"
  hostname: {{ .Values.mapping.hostname }}
  prefix: {{ .Values.mapping.prefix | trimSuffix "/" }}/rpc/load-artifacts
  rewrite: {{ .Values.mapping.rewrite | trimSuffix "/" }}/rpc/load-artifacts
  timeout_ms: {{ .Values.mapping.timeout_ms_loadartifacts }}
{{ end }}
