image:
  repository: "ghga/state-management-service"

configPrefix: sms

# Service base path 
apiBasePath: /sms/
# This parameter is used as Kafka's group id
serviceName: sms-rest
# This parameter specifies the client id in Kafka
serviceInstanceId: sms-rest-1

parameters:
  default:
    host: 0.0.0.0
    db_connection_str: null
    db_permissions:
    - "*.*:*"
    allow_empty_prefix: true
    db_prefix: ""
    token_hashes: []
    log_level: DEBUG
    object_storages: {}

containers:
- name: rest
  type: "rest"
  cmd: sms
  config:
    name: parameters
    key: parameters

# SMS is just used for testing, it requires access to all topics to clear them
kafkaTopicsParameters: false

topics:
  wildcard:
    topic:
      name: wildcard
      value: '*'
