image:
  repository: "ghga/state-management-service"

config_prefix: sms

parameters:
  default:
    host: 0.0.0.0
    db_connection_str: null
    db_permissions:
    - "*.*:*"
    allow_empty_prefix: true
    db_prefix: ""
    token_hashes: []
    service_instance_id: 'rest.1'
    log_level: DEBUG
    object_storages: {}

containers:
- name: rest
  type: "rest"
  cmd: sms
  config:
    name: parameters
    key: parameters
