apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-km-jobs.fullname" . }}
  labels:
    {{- include "auth-km-jobs.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.envVars }}
  {{ print $.Values.envPrefix "_" $k | upper }}: {{ $v }}
  {{- end }}
