apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  schedule: {{ .Values.cronSchedule }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      template:
        metadata:
          annotations:
            {{- if .Values.podAnnotations }}
            {{- toYaml .Values.podAnnotations | nindent 12 }}
            {{- end }}
        spec:
          serviceAccountName: {{ .Values.serviceAccount.name }}
          {{- if .Values.imagePullSecretNames }}
          {{- include "ghga-common.image-pull-secrets" .  | nindent 10 }}
          {{- end }}
          containers:
          - image: "{{ .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.tag }}"
            {{- if eq .Values.service.keyType "internal" }}
            {{- include "ghga-common.command-args" (list .Values.service.runCommands.internal )  | nindent 12 }}
            {{- else if eq .Values.service.keyType "external" }}
            {{- include "ghga-common.command-args" (list .Values.service.runCommands.external )  | nindent 12 }}
            {{- else if eq .Values.service.keyType "wps" }}
            {{- include "ghga-common.command-args" (list .Values.service.runCommands.wps )  | nindent 12 }}
            {{- else }}
            {{- fail "value for .Values.service.keyType must be `internal` or `external`" }}
            {{- end }}
            name: {{ include "auth-km-jobs.fullname" . }}
            envFrom:
              - configMapRef:
                  name: {{ include "auth-km-jobs.fullname" . }}
            securityContext:
              runAsUser: 1000
              capabilities:
                drop:
                  - ALL
              seccompProfile:
                type: "RuntimeDefault"
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              allowPrivilegeEscalation: false
          restartPolicy: Never
