image:
  repository: "ghga/download-controller-service"

configPrefix: dcs

# Service parameters

# Service base path
apiBasePath: /ga4gh/drs/v1/
# Name of the database
dbName: download-controller
# This parameter is used as Kafka's group id
serviceName: dcs-rest
# This parameter specifies the client id in Kafka
serviceInstanceId: dcs-rest-1
# This parameter is used as Kafka's group id
serviceNameConsumer: dcs-consumer
# This parameter specifies the client id in Kafka
serviceInstanceIdConsumer: dcs-consumer-1

parameters:
  default:
    auth_key: '{}'
    db_connection_str: null
    drs_server_uri: drs://localhost:8080/
    ekss_base_url: http://encryption-key-store:8080
    host: "0.0.0.0"
    presigned_url_expires_after: 10
    object_storages: {}
    unstaged_download_collection: unstaged-download-requested

containers:
- name: rest
  type: "rest"
  cmd: dcs run-rest
  config:
    name: parameters-rest
    key: parameters-rest
- name: consumer
  type: "consumer"
  cmd: dcs consume-events
  config:
    name: parameters-consumer
    key: parameters-consumer


topics:
  fileRegisteredEvent:
    topic:
      name: file_registered_event_topic
      value: downloads
    types:
      - name: file_registered_event_type
        value: drs_object_registered
  fileDeletedEvent:
    topic:
      name: file_deleted_event_topic
      value: downloads
    types:
      - name: file_deleted_event_type
        value: drs_object_deleted
  filesToRegister:
    topic:
      name: files_to_register_topic
      value: internal-registrations
    types:
      - name: files_to_register_type
        value: internal_file_registered
  filesToDelete:
    topic:
      name: files_to_delete_topic
      value: purges
  downloadServed:
    topic:
      name: download_served_event_topic
      value: downloads
    types:
      - name: download_served_event_type
        value: drs_object_served
  unstagedDownload:
    topic:
      name: unstaged_download_event_topic
      value: downloads
