image:
  repository: "ghga/download-controller-service"

config_prefix: dcs

parameters:
  default:
    auth_key: '{}'
    cors_allow_credentials: false
    cors_allowed_headers: []
    cors_allowed_methods: []
    cors_allowed_origins: []
    db_connection_str: null
    db_name: dcs
    drs_server_uri: drs://localhost:8080/
    ekss_base_url: http://encryption-key-store:8080
    host: "0.0.0.0"
    presigned_url_expires_after: 10
    object_storages: {}
    service_instance_id: 'dcs_1'
    unstaged_download_collection: unstaged-download-requested
  rest:
    service_instance_id: 'rest.1'
  consumer:
    service_instance_id: 'consumer.1'

containers:
- name: rest
  type: "rest"
  cmd: dcs run-rest
  config:
    name: parameters-rest
    key: parameters-rest
- name: consumer
  type: "consumer"
  cmd: dcs consume-events
  config:
    name: parameters-consumer
    key: parameters-consumer


topics:

  fileRegisteredEvent:
    topic:
      name: file_registered_event_topic
      value: downloads
    type:
      name: file_registered_event_type
      value: drs_object_registered

  fileDeletedEvent:
    topic:
      name: file_deleted_event_topic
      value: downloads
    type:
      name: file_deleted_event_type
      value: drs_object_deleted

  filesToRegister:
    topic:
      name: files_to_register_topic
      value: internal-registrations
    type:
      name: files_to_register_type
      value: internal_file_registered

  filesToDelete:
    topic:
      name: files_to_delete_topic
      value: purges

  downloadServed:
    topic:
      name: download_served_event_topic
      value: downloads
    type:
      name: download_served_event_type
      value: drs_object_served

  unstagedDownload:
    topic:
      name: unstaged_download_event_topic
      value: downloads
