image:
  repository: "ghga/test-oidc-provider"

config_prefix: top

ingress:
  enabled: false

mapping:
  enabled: false

parameters:
  default:
    api_root_path: ""
    auto_reload: false
    client_id: test-client
    cors_allow_credentials: null
    cors_allowed_headers: null
    cors_allowed_methods: null
    cors_allowed_origins: null
    docs_url: /docs
    host: 0.0.0.0
    issuer: https://op.test

    openapi_url: /openapi.json
    port: 8080
    service_name: top

    user_domain: home.org
    valid_seconds: 3600
    workers: 1

    service_instance_id: rest.1

kafkaSecrets:
  enabled: false


containers:
- name: rest
  type: "rest"
  cmd: top
  config:
    name: parameters
    key: parameters
