image:
  repository: "ghga/test-oidc-provider"

config_prefix: top

parameters:
  default:
    host: 0.0.0.0
    service_instance_id: rest.1

containers:
- name: rest
  type: "rest"
  cmd: top
  config:
    name: parameters
    key: parameters
