yamlApplicationConfig:
  kafka:
    clusters:
      - name: kafka-dev
        bootstrapServers:  kafka-dev:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false
