image:
  repository: "ghga/access-request-service"

config_prefix: ars

parameters:
  default:
    auth_key: '{}'
    db_connection_str: null
    db_name: ars
    download_access_url: http://claims-repository:8080/download-access
    host: "0.0.0.0"
    service_instance_id: 'rest.1'

containers:
- name: rest
  type: "rest"
  cmd: ars
  config:
    name: parameters
    key: parameters

topics:
  fileRegisteredEvent:
    topic:
      name: access_request_events_topic
      value: access_requests
    types:
    - name: access_request_created_event_type
      value: access_request_created
    - name: access_request_allowed_event_type
      value: access_request_allowed
    - name: access_request_denied_event_type
      value: access_request_denied
