args: []
command: []
horizontalPodAutoscaler:
  enabled: false
  averageCpuUtilization: 75
  averageMemoryUtilization: 75
image:
  name: "ghga/access-request-service"
podAnnotations: {}
port: "8080"
resources:
  limits:
    cpu: "500m"
    memory: "256M"
  requests:
    cpu: "100m"
    memory: "64M"

config_prefix: ars

ingress:
  enabled: false
  annotations: {}
  hostname: ""
  prefix: /
  tls:
    enabled: false
    secretName: ""

mapping:
  enabled: false
  hostname: ""
  prefix: /
  rewrite: null
  ambassador_id: null
  timeout_ms: null

parameters:
  default:
    access_grant_max_days: 730
    access_grant_min_days: 7
    access_upfront_max_days: 180
    api_root_path: ""
    auth_algs:
    - ES256
    auth_check_claims:
      email: null
      exp: null
      iat: null
      name: null
      id: null
    auth_key: '{}'
    auth_map_claims: {}
    auto_reload: true
    cors_allow_credentials: false
    cors_allowed_headers: []
    cors_allowed_methods: []
    cors_allowed_origins: []
    data_steward_email: helpdesk@ghga.de
    db_connection_str: null
    db_name: ars
    docs_url: /docs
    download_access_url: http://claims-repository-svc:8080/download-access
    host: "0.0.0.0"
    kafka_servers:
    - kafka-kafka-bootstrap:9092
    kafka_security_protocol: PLAINTEXT
    kafka_ssl_cafile: null
    kafka_ssl_certfile: null
    kafka_ssl_keyfile: null
    kafka_ssl_password: null
    access_request_events_topic: access_request_events
    access_request_created_event_type: access_request_created
    access_request_allowed_event_type: access_request_allowed
    access_request_denied_event_type: access_request_denied
    openapi_url: /openapi.json
    port: 8080
    service_instance_id: 'rest.1'
    service_name: ars
    workers: 1

shareProcessNamespace: false
