image:
  repository: "ghga/access-request-service"

config_prefix: ars

# Service parameters

# Service base path 
apiBasePath: /ars/
# Name of the database
dbName: access-request
# This parameter is used as Kafka's group id
serviceName: ars-rest
# This parameter specifies the client id in Kafka
serviceInstanceId: ars-rest-1

# Those values are directly injected into the service's configuration
parameters:
  default:
    auth_key: '{}'
    db_connection_str: null
    download_access_url: http://claims-repository:8080/download-access
    host: "0.0.0.0"

containers:
- name: rest
  type: "rest"
  cmd: ars
  config:
    name: parameters
    key: parameters

topics:
  fileRegisteredEvent:
    topic:
      name: access_request_events_topic
      value: access-requests
    types:
    - name: access_request_created_event_type
      value: access_request_created
    - name: access_request_allowed_event_type
      value: access_request_allowed
    - name: access_request_denied_event_type
      value: access_request_denied
