apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: data-portal-ui
  name: data-portal-ui
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: data-portal-ui
  template:
    metadata:
      annotations:
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        app: data-portal-ui
        sidecar.istio.io/inject: "true"
        version: staging
    spec:
      serviceAccountName: data-portal-ui
      containers:
      - env:
        - name: DATA_PORTAL_UI_HOST
          value: "0.0.0.0"
        - name: DATA_PORTAL_UI_PORT
          value: {{ .Values.port }}
        - name: DATA_PORTAL_UI_SVC_REPOSITORY_URL
          value: {{ .Values.svcRepositoryUrl }}
        - name: DATA_PORTAL_UI_SVC_SEARCH_URL
          value: {{ .Values.svcSearchUrl }}
        - name: REACT_APP_CLIENT_URL
          value: {{ .Values.clientUrl }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        {{- include "ghga-common.command" (list "python /service/configure_build_serve/run.py")  | nindent 8 }}
        name: data-portal-ui
        securityContext:
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
          #readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: "RuntimeDefault"
        ports:
        - containerPort: {{ .Values.port }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.port }}
          initialDelaySeconds: 240
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: {{ .Values.port }}
          initialDelaySeconds: 240
          periodSeconds: 15
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
      restartPolicy: Always
      volumes: null
