apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  annotations:
    configmap-hash: {{ include (print $.Template.BasePath "/configmap.yml") . | sha256sum }}
  labels:
    app: {{ .Release.Name }}
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        configmap-hash: {{ include (print $.Template.BasePath "/configmap.yml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        app: {{ .Release.Name }}
        {{- include "ghga-common.pod-extra-labels" .  | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      shareProcessNamespace: {{ .Values.shareProcessNamespace }}
      {{- if .Values.imagePullSecretNames }}
      {{- include "ghga-common.image-pull-secrets" .  | nindent 6 }}
      {{- end }}
      containers:
      - image: "{{ .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        {{- include "ghga-common.command-args" (list "python /service/configure_build_serve/run.py")  | nindent 8 }}
        name: {{ .Release.Name }}
        securityContext:
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
          #readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: "RuntimeDefault"
        ports:
        - containerPort: {{ .Values.port }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.port }}
          initialDelaySeconds: 240
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: {{ .Values.port }}
          initialDelaySeconds: 240
          periodSeconds: 15
        volumeMounts:
        - name: config
          mountPath: "/home/node/.{{ .Values.config_prefix }}.yaml"
          subPath: .{{ .Values.config_prefix }}.yaml
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}
          items:
          - key: parameters
            path: .{{ .Values.config_prefix }}.yaml
      restartPolicy: Always
