apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
    version: "1"
  name: {{ .Release.Name }}-svc
spec:
  type: ClusterIP
  ports:
  - name: tcp-web
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
  selector:
    app: {{ .Release.Name }}
