image:
  repository: "ghga/work-package-service"

config_prefix: wps

# Service parameters

# Service base path 
apiBasePath: /wps/
# Name of the database
dbName: work-package
# This parameter is used as Kafka's group id
serviceName: wps-rest
# This parameter specifies the client id in Kafka
serviceInstanceId: wps-rest-1
# This parameter is used as Kafka's group id
serviceNameConsumer: wps-consumer
# This parameter specifies the client id in Kafka
serviceInstanceIdConsumer: wps-consumer-1

parameters:
  default:
    auth_key: '{}'
    db_connection_str: null
    db_name: wps
    download_access_url: http://claims-repository:8080/download-access
    host: "0.0.0.0"
    service_instance_id: 'wps_1'
    service_name: wps
    work_package_signing_key: '{}'
  rest:
    service_instance_id: 'rest.1'
  consumer:
    service_instance_id: 'consumer.1'

containers:
- name: rest
  type: "rest"
  cmd: wps run-rest
  config:
    name: parameters-rest
    key: parameters-rest
- name: consumer
  type: "consumer"
  cmd: wps consume-events
  config:
    name: parameters-consumer
    key: parameters-consumer

topics:
  datasetChangeEvent:
    topic:
      name: dataset_change_event_topic
      value: metadata-datasets
    types:
    - name: dataset_upsertion_event_type
      value: dataset_created
    - name: dataset_deletion_event_type
      value: dataset_deleted