image:
  repository: "ghga/well-known-value-service"

config_prefix: wkvs

parameters:
  default:
    crypt4gh_public_key: dWoWghAEVPcpHILEb5drJx59nF+of6YKuAOhKRpmegY=
    dcs_api_url: http://download-controller/download
    host: "0.0.0.0"
    ucs_api_url: http://upload-controller/upload
    wps_api_url: http://work-package/

containers:
- name: rest
  type: "rest"
  cmd: wkvs
  config:
    name: parameters
    key: parameters
