args: []
command: []
horizontalPodAutoscaler:
  enabled: false
  averageCpuUtilization: 75
  averageMemoryUtilization: 75
image:
  name: "ghga/well-known-value-service"
podAnnotations: {}
port: "8080"
resources:
  limits:
    cpu: "500m"
    memory: "256M"
  requests:
    cpu: "100m"
    memory: "64M"

config_prefix: wkvs

ingress:
  enabled: false
  annotations: []
  hostname: ""
  prefix: /
  tls:
    enabled: false
    secretName: ""

mapping:
  enabled: false
  hostname: ""
  prefix: /
  rewrite: null

parameters:
  default:
    api_root_path: /
    auto_reload: false
    cors_allow_credentials: null
    cors_allowed_headers: null
    cors_allowed_methods: null
    cors_allowed_origins: null
    crypt4gh_public_key: dWoWghAEVPcpHILEb5drJx59nF+of6YKuAOhKRpmegY=
    dcs_api_url: http://127.0.0.1/download
    docs_url: /docs
    host: "0.0.0.0"
    log_level: info
    openapi_url: /openapi.json
    port: 8080
    service_name: wkvs
    ucs_api_url: http://127.0.0.1/upload
    workers: 1
    wps_api_url: http://127.0.0.1

shareProcessNamespace: false
