{{ if .Values.authService.emissary.enabled }}
apiVersion: getambassador.io/v3alpha1
kind: AuthService
metadata:
  name: {{ .Values.authService.emissary.name}}
spec:
  auth_service: "{{ .Chart.Name }}.{{ .Release.Namespace }}:{{ .Values.port }}"
  allowed_request_headers:
    - "X-Authorization"
{{ end }}
