apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-adapter
  name: auth-adapter
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: auth-adapter
  template:
    metadata:
      annotations:
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        app: auth-adapter
        version: staging
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: auth-adapter
      containers:
        - env:
            - name: AUTH_SERVICE_RUN_AUTH_ADAPTER
              value: "true"
            - name: AUTH_SERVICE_HOST
              value: 0.0.0.0
            - name: AUTH_SERVICE_PORT
              value: "8080"
            - name: AUTH_SERVICE_DB_NAME
              value: auth-db
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
          {{- end }}
          name: auth-adapter
          securityContext:
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: "RuntimeDefault"
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 256M
            requests:
              cpu: 100m
              memory: 64M
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
      restartPolicy: Always
