apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
    version: "1"
  name: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
    - name: tcp-web
      port: 8080
      targetPort: 8080
  selector:
    app: {{ .Chart.Name }}
