apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metadata-search-service
  name: metadata-search-service
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: metadata-search-service
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-secret-variables: 'secret/metadata-repository-service/data'
        vault.hashicorp.com/agent-inject-template-variables: |
          {{ with secret "secret/metadata-repository-service/data" -}}
          export METADATA_SEARCH_SERVICE_DB_URL={{ .Data.data.db_url }}
          {{- end }}
        vault.hashicorp.com/role: "metadata-repository-service-role"
        vault.hashicorp.com/agent-run-as-same-user: "true"
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      labels:
        app: metadata-search-service
        version: staging
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: metadata-repository-service
      containers:
      - args:
          - |
            source /vault/secrets/variables
            shred /vault/secrets/variables
            metadata-search-service
        command:
          - bash
          - -c
        env:
        - name: METADATA_SEARCH_SERVICE_API_ROOT_PATH
          value: {{ .Values.apiRootPath }}
        - name: METADATA_SEARCH_SERVICE_CORS_ALLOWED_HEADERS
          value: {{ .Values.corsAllowedHeaders }}
        - name: METADATA_SEARCH_SERVICE_CORS_ALLOWED_METHODS
          value: {{ .Values.corsAllowedMethods }}
        - name: METADATA_SEARCH_SERVICE_CORS_ALLOWED_ORIGINS
          value: {{ .Values.corsAllowedOrigins }}
        - name: METADATA_SEARCH_SERVICE_CORS_ALLOW_CREDENTIALS
          value: {{ .Values.corsAllowedCredentials }}
        - name: METADATA_SEARCH_SERVICE_DB_NAME
          value: {{ .Values.dbName }}
        - name: METADATA_SEARCH_SERVICE_HOST
          value: {{ .Values.serviceHost }}
        - name: METADATA_SEARCH_SERVICE_PORT
          value: {{ .Values.servicePort }}
        - name: METADATA_SEARCH_SERVICE_LOG_LEVEL
          value: {{ .Values.logLevel }}
        image: ghga/metadata-search-service:0.0.0-43-1a72aeb-main
        name: metadata-search-service
        ports:
        - containerPort: {{ .Values.servicePort }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        securityContext:
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: "RuntimeDefault"
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        readinessProbe:
          tcpSocket:
            port: {{ .Values.servicePort }}
          initialDelaySeconds: 10
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: {{ .Values.servicePort }}
          initialDelaySeconds: 10
          periodSeconds: 15
