resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "256Mi"

mapping:
  enabled: true
  hostname: data.ghga-dev.de
  prefix: /api/repository/

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-init-first: "true"
  vault.hashicorp.com/tls-skip-verify: "true"
  vault.hashicorp.com/agent-pre-populate-only: "true"
  vault.hashicorp.com/agent-run-as-same-user: "true"
  vault.hashicorp.com/role: "metadata-repository-role"
  vault.hashicorp.com/agent-inject-secret-db: "secret/data/metadata-repository"
  vault.hashicorp.com/agent-inject-template-db: |
    {{ with secret "secret/data/metadata-repository" -}}
    export METADATA_REPOSITORY_SERVICE_DB_URL="{{ .Data.data.DB_URL }}"
    {{- end }}

parameters:
  db_name: metadata-demo
