apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  parameters: |
    {{- if .Values.parameters.default }}
    default:
    {{- toYaml .Values.parameters.default | nindent 5 }}
    {{- else }}
    default:
    {{- toYaml .Values.parameters | nindent 5 }}
    {{- end }}
