args: []
command: []
horizontalPodAutoscaler:
  enabled: false
  averageCpuUtilization: 75
  averageMemoryUtilization: 75
image:
  name: "ghga/data-portal-ui"
podAnnotations: {}
port: "8080"
resources:
  limits:
    cpu: "1500m"
    memory: "2048M"
  requests:
    cpu: "1000m"
    memory: "1024M"

config_prefix: data_portal_ui

ingress:
  enabled: false
  annotations: {}
  hostname: ""
  prefix: /
  tls:
    enabled: false
    secretName: ""

mapping:
  enabled: false
  hostname: ""
  prefix: /

parameters:
  default:
    host: "0.0.0.0"
    port: 8080
    mass_url: "/api/mass"
    metldata_url: "/api/metldata"

shareProcessNamespace: false
serviceCommand: python /service/configure_build_serve/run.py
