args: []
command: []
horizontalPodAutoscaler:
  enabled: false
  averageCpuUtilization: 75
  averageMemoryUtilization: 75
image:
  name: "ghga/data-portal-ui"
podAnnotations: {}
port: "8080"
resources:
  limits:
    cpu: "1500m"
    memory: "2048M"
  requests:
    cpu: "1000m"
    memory: "1024M"

config_prefix: data_portal_ui

ingress:
  enabled: false
  annotations: {}
  hostname: ""
  prefix: /
  tls:
    enabled: false
    secretName: ""

mapping:
  enabled: false
  hostname: ""
  prefix: /
  rewrite: null
  ambassador_id: null
  timeout_ms: null

parameters:
  default:
    host: 0.0.0.0
    port: 8080

    ars_url: "/api/ars"
    auth_url: "/api/auth"
    mass_url: "/api/mass"
    metldata_url: "/api/metldata"
    wps_url: "/api/wps"

    oidc_authority_url: https://login.aai.lifescience-ri.eu/oidc/
    oidc_authorization_url: authorize
    oidc_token_url: token
    oidc_userinfo_url: userinfo
    oidc_use_discovery: false

shareProcessNamespace: false

# Add extra labels to the service pod
# podExtraLabels:
#   my-label: my-value
