image:
  repository: "ghga/data-portal-ui"

config_prefix: data_portal_ui

parameters:
  default:
    host: 0.0.0.0
    port: 8080

    ars_url: "/api/ars"
    auth_url: "/api/auth"
    mass_url: "/api/mass"
    metldata_url: "/api/metldata"
    wps_url: "/api/wps"

    oidc_authority_url: https://login.aai.lifescience-ri.eu/oidc/
    oidc_authorization_url: authorize
    oidc_token_url: token
    oidc_userinfo_url: userinfo
    oidc_use_discovery: false


containerSecurityContext:
  readOnlyRootFilesystem: false

# Type needs to be fixed, it is used for exposed pods and probes
containers:
- name: rest
  type: "rest"
  cmd: "python /service/configure_build_serve/run.py"
  config:
    name: parameters
    key: parameters
    appuser: node
