args: []
command: []
horizontalPodAutoscaler:
  enabled: false
  averageCpuUtilization: 75
  averageMemoryUtilization: 75
image:
  name: "ghga/data-portal-ui"
  tag: "0.1.0"
podAnnotations: {}
port: "8080"
resources:
  limits:
    cpu: "1500m"
    memory: "2048M"
  requests:
    cpu: "1000m"
    memory: "1024M"

config_prefix: data_portal_ui

mapping:
  enabled: false
  hostname: ""
  prefix: /

parameters:
  host: "0.0.0.0"
  port: 8080
  svc_repository_url: "/api/repository"
  svc_search_url: "/api/search"
