podAnnotations: {}
command: []
args: []
image:
  name: "ghga/data-portal-ui"
  tag: "0.0.0-193-6587ec5-main"
port: "8080"
serviceTargetPort: "8080"
svcRepositoryUrl: "/api/repository"
svcSearchUrl: "/api/search"
clientUrl: "https://data.ghga-dev.de/"
resources:
  limits:
    cpu: "1500m"
    memory: "2048M"
  requests:
    cpu: "1000m"
    memory: "1024M"
