args: []
command: []
horizontalPodAutoscaler:
  enabled: false
  averageCpuUtilization: 75
  averageMemoryUtilization: 75
image:
  name: "ghga/auth-service"
podAnnotations: {}
port: "8080"
resources:
  limits:
    cpu: "1500m"
    memory: "2048M"
  requests:
    cpu: "1000m"
    memory: "1024M"

config_prefix: auth_service

mapping:
  enabled: false
  hostname: ""
  prefix: /
  rewrite: null

parameters:
  # Specify execution mode as auth-adapter, user-registry or claims-repository
  run_auth_adapter: null
  include_apis: null

  # Injected through Vault
  auth_ext_keys: null
  auth_key: null
  db_url: null

  # Required for auth-adapter only and injected through Vault
  basic_auth_credentials: null
  oidc_client_id: ghga-data-portal

  # Required for auth-adapter only
  oidc_authority_url: https://proxy.aai.lifescience-ri.eu
  oidc_userinfo_endpoint: null

  add_as_data_stewards: []
  api_ext_path: /api/auth
  api_root_path: /
  auth_algs:
  - ES256
  auth_check_claims:
    email: null
    exp: null
    iat: null
    name: null
  auth_ext_algs:
  - RS256
  - ES256
  auth_map_claims: {}
  auto_reload: true
  basic_auth_realm: GHGA Data Portal
  claims_collection: claims
  cors_allow_credentials: null
  cors_allowed_headers: null
  cors_allowed_methods: null
  cors_allowed_origins: null
  db_name: auth-db
  docs_url: /docs
  host: 0.0.0.0
  log_level: debug
  openapi_url: /openapi.json
  organization_url: https://ghga.de
  port: 8080
  service_name: auth_service
  users_collection: users
  workers: 1

authService:
  emissary:
    enabled: false
    name: authentication

shareProcessNamespace: false
