image:
  repository: "ghga/auth-service"

config_prefix: auth_service

parameters:
  default:
    db_connection_str: null
    host: 0.0.0.0

authService:
  emissary:
    enabled: false
    name: authentication

containers:
- name: rest
  type: "rest"
  cmd: auth-service
  config:
    name: parameters
    key: parameters

topics:
  authEvents:
    topic:
      name: auth_events_topic
      value: auth
    types:
    - name: second_factor_recreated_event_type
      value: second_factor_recreated
  ivaEvents:
    topic:
      name: iva_events_topic
      value: ivas
    types:
    - name: iva_state_changed_event_type
      value: iva_state_changed
  datasetDeletionEvent:
    topic:
      name: dataset_deletion_event_topic
      value: metadata-datasets
    types:
    - name: dataset_deletion_event_type
      value: dataset_deleted
