args: []
command: []
horizontalPodAutoscaler:
  enabled: false
  averageCpuUtilization: 75
  averageMemoryUtilization: 75
image:
  name: "ghga/mass"
podAnnotations: {}
port: "8080"
resources:
  limits:
    cpu: "500m"
    memory: "256M"
  requests:
    cpu: "100m"
    memory: "64M"

config_prefix: mass

ingress:
  enabled: false
  annotations: {}
  hostname: ""
  prefix: /
  tls:
    enabled: false
    secretName: ""

mapping:
  enabled: false
  hostname: ""
  prefix: /
  rewrite: null
  ambassador_id: null
  timeout_ms: null

parameters:
  default:
    api_root_path: /
    auto_reload: false
    cors_allow_credentials: null
    cors_allowed_headers: null
    cors_allowed_methods: null
    cors_allowed_origins: null
    db_connection_str: null
    db_name: metadata-store
    docs_url: /docs
    host: "0.0.0.0"
    kafka_servers:
    - kafka:9092

    openapi_url: /openapi.json
    port: 8080
    resource_change_event_topic: searchable_resources
    resource_deletion_event_type: searchable_resource_deleted
    resource_upsertion_event_type: searchable_resource_upserted
    searchable_classes:
      EmbeddedDataset:
        description: Dataset grouping files under controlled access.
        facetable_properties:
        - key: alias
          name: Alias
        - key: title
          name: Title
    service_name: mass
    workers: 1
  rest:
    service_instance_id: 'mass_rest_1'
  consumer:
    service_instance_id: 'mass_consumer_1'

shareProcessNamespace: false
