image:
  repository: "ghga/mass"

config_prefix: mass

parameters:
  default:
    db_connection_str: null
    db_name: metadata-store
    host: "0.0.0.0"
    searchable_classes:
      EmbeddedDataset:
        description: Dataset grouping files under controlled access.
        facetable_fields:
        - key: alias
          name: Dataset alias
        - key: title
          name: Dataset title
        selected_fields:
        - key: alias
          name: Dataset alias
        - key: title
          name: Dataset title
  rest:
    service_instance_id: 'rest.1'
  consumer:
    service_instance_id: 'consumer.1'

containers:
- name: rest
  type: "rest"
  cmd: mass run-rest
  config:
    name: parameters-rest
    key: parameters-rest
- name: consumer
  type: "consumer"
  cmd: mass consume-events
  config:
    name: parameters-consumer
    key: parameters-consumer


topics:
  resourceChangeEvent:
    topic:
      name: resource_change_event_topic
      value: searchable_resources
    types:
    - name: resource_deletion_event_type
      value: searchable_resource_deleted
    - name: resource_upsertion_event_type
      value: searchable_resource_upserted
