image:
  repository: "ghga/data-portal-ui"

configPrefix: data_portal_ui

# Service parameters

parameters:
  default:
    host: 0.0.0.0
    oidc_use_discovery: false


containerSecurityContext:
  readOnlyRootFilesystem: false

# Type needs to be fixed, it is used for exposed pods and probes
containers:
- name: rest
  type: "rest"
  cmd: "python /service/configure_build_serve/run.py"
  config:
    name: parameters
    key: parameters
    appuser: node
