image:
  repository: "ghga/data-portal"

configPrefix: data_portal

# Service parameters

parameters:
  default:
    host: 0.0.0.0
    oidc_use_discovery: false


containerSecurityContext:
  readOnlyRootFilesystem: false
  # In Data-Portal-UI, node is user 1000 and appuser is user 1001
  runAsUser: 1001

# Type needs to be fixed, it is used for exposed pods and probes
containers:
- name: rest
  type: "rest"
  cmd: "node /home/appuser/run.mjs"
  config:
    name: parameters
    key: parameters
    appuser: appuser
    mountPath: /home/appuser/data-portal.yaml