image:
  repository: "ghga/data-portal"

configPrefix: data_portal
apiBasePath: /

# Service parameters
config:
  host: 0.0.0.0
  oidc_use_discovery: false

configMap:
  mountPath: /home/appuser/data-portal.yaml

containerSecurityContext:
  readOnlyRootFilesystem: false
  # In Data-Portal-UI, node is user 1000 and appuser is user 1001
  runAsUser: 1001

cmd: "node /home/appuser/run.mjs"
