args: []
command: []
horizontalPodAutoscaler:
  enabled: false
  averageCpuUtilization: 75
  averageMemoryUtilization: 75
image:
  name: "ghga/metldata"
podAnnotations: {}
port: "8080"
resources:
  limits:
    cpu: "500m"
    memory: "256M"
  requests:
    cpu: "100m"
    memory: "64M"

config_prefix: metldata

ingress:
  enabled: false
  annotations: {}
  hostname: ""
  prefix: /
  tls:
    enabled: false
    secretName: ""

mapping:
  enabled: false
  hostname: ""
  prefix: /
  rewrite: null
  ambassador_id: null
  timeout_ms: null
  timeout_ms_loadartifacts: 600000

parameters:
  default:
    api_root_path: /
    artifact_infos: []
    auto_reload: false
    cors_allow_credentials: false
    cors_allowed_headers: []
    cors_allowed_methods: []
    cors_allowed_origins: []
    dataset_change_event_topic: metadata_datasets
    dataset_deletion_type: dataset_deleted
    dataset_upsertion_type: dataset_created
    db_connection_str: null
    db_name: metadata_artifacts
    docs_url: /docs
    host: 0.0.0.0
    kafka_servers:
    - kafka:9092
    kafka_security_protocol: PLAINTEXT
    kafka_ssl_cafile: null
    kafka_ssl_certfile: null
    kafka_ssl_keyfile: null
    kafka_ssl_password: null
    loader_token_hashes: null  # <Please fill - The tokens must be the loader token generated using the data steward kit.>

    openapi_url: /openapi.json
    port: 8080
    primary_artifact_name: embedded_public
    primary_dataset_name: EmbeddedDataset
    resource_change_event_topic: searchable_resources
    resource_deletion_event_type: searchable_resource_deleted
    resource_upsertion_type: searchable_resource_upserted
    service_instance_id: 'rest.1'
    workers: 1

shareProcessNamespace: false
kafkaSecrets:
  enabled: false
