environments:
  default:
    values:
    - config/default.yaml
    kubeContext: kind-kind
  dev:
    values:
    - config/dev.yaml
    kubeContext: GHGAinfra
  prod:
    values:
    - config/prod.yaml
    kubeContext: GHGAprod2
