environments:
  default:
    values:
    - config/default.yaml
    kubeContext: docker-desktop
  dev:
    values:
    - config/default.yaml
    - config/dev.yaml
    kubeContext: GHGAinfra
  prod:
    values:
    - config/default.yaml
    - config/prod.yaml
    kubeContext: GHGAprod2
