bases:
- environments.yaml

repositories:
 - name: ghga
   url: https://ghga-de.github.io/charts/

helmDefaults:
  wait: true

templates:
  default: &default
    version: ~0.0.1
    namespace: testing
    values:
    - config/{{`{{ .Release.Name }}`}}/default.yaml
    - config/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml

releases:
- name: auth-adapter
  chart: ghga/auth-adapter
  <<: *default

- name: auth-km-cronjob
  chart: ghga/auth-km-cronjob
  <<: *default

- name: auth-km-ext-cronjob
  chart: ghga/auth-km-cronjob
  <<: *default

- name: data-portal-ui
  chart: ghga/data-portal-ui
  <<: *default
