apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "remotebackup.fullname" . }}-config-yaml
  labels:
    {{- include "remotebackup.labels" . | nindent 4 }}
data: 
   config.yaml: |
      {{- if .Values.parameters }}
      {{- toYaml .Values.parameters | nindent 6 }}
      {{- end}}
