args: []
command: []
horizontalPodAutoscaler:
  enabled: false
  averageCpuUtilization: 75
  averageMemoryUtilization: 75
image:
  name: "ghga/metadata-search-service"
podAnnotations: {}
port: "8080"
resources:
  limits:
    cpu: "500m"
    memory: "256M"
  requests:
    cpu: "100m"
    memory: "64M"

config_prefix: metadata_search_service

mapping:
  enabled: false
  hostname: ""
  prefix: /

parameters:
  api_root_path: /
  auto_reload: true
  cors_allow_credentials: false
  cors_allowed_headers: []
  cors_allowed_methods: []
  cors_allowed_origins: []
  db_name: metadata-store
  db_url: "**********"
  docs_url: /docs
  host: 0.0.0.0
  log_level: info
  openapi_url: /openapi.json
  port: 8080
  workers: 1

shareProcessNamespace: false
