name: Bump and lint Charts per directory
on:
  pull_request:
    types:
      - labeled

  workflow_dispatch:
    inputs:
      chart-dirs:
        required: true
        default: ""
      library-chart-version:
        required: true
        default: "0.0.0"

jobs:
  update-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set variables
        shell: bash
        run: |
          if [ "${{ github.event.inputs.chart-dirs }}" == "" ]; then
            # Get modified Chart.yaml files, excluding "jobs" directory
            changed_charts=$(git --no-pager diff --name-only --diff-filter=M origin/${{ github.event.repository.default_branch }} | grep "Chart.yaml" | grep -v "jobs")
          else
            changed_charts=$(echo ${{ github.event.inputs.chart-dirs }} | tr "," "\n" | xargs -I {} find {} -name "Chart.yaml")
          fi
          
          # Extract parent directories (nested and top-level)
          chart_dirs_nested=$(echo "$changed_charts" | xargs -I {} python3 -c 'from pathlib import Path; print(Path("{}").parent.parent)' | sort -u | paste -sd "," -)
          chart_dirs=$(echo "$changed_charts" | xargs -I {} python3 -c 'from pathlib import Path; print(Path("{}").parts[0])' | sort -u | paste -sd "," -)
          
          echo "Processing charts in directories: $chart_dirs"
          echo "CHART_DIRS_NESTED=$chart_dirs_nested" >> $GITHUB_ENV
          echo "CHART_DIRS=$chart_dirs" >> $GITHUB_ENV
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
        # New version of ruamel.yaml contains fix for https://sourceforge.net/p/ruamel-yaml/tickets/529/
        # However, this adds a trailing white space to the Chart.yaml file, which is not compatible with the linter.
      - name: Install dependencies for scripts
        shell: bash
        run: pip install semver ruamel.yaml==0.18.12 requests
      - name: Add charts' dependency repositories
        shell: bash
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add ghga https://ghga-de.github.io/charts
      # This step should be idempotent, only bumping to the largest version difference
      # Bumps either by appVersion or library chart version
      - name: Bump Chart version and update dependencies
        shell: bash
        run: |
          for chart_dir in ${CHART_DIRS//,/ }; do
            python ./scripts/bump_charts.py --chart-dir $chart_dir --library-chart-version ${{ github.event.inputs.library-chart-version }}
          done
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1   
      - name: Set chart directories
        shell: bash
        run: |
          changed=$(ct list-changed --chart-dirs $CHART_DIRS_NESTED --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            ct lint --chart-dirs $CHART_DIRS_NESTED --target-branch ${{ github.event.repository.default_branch }} --validate-maintainers=false
          fi
      - name: Update branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Apply automatic changes"
