name: helmfile-template
on:
  push:
    branches:
      - main

jobs:
  template-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ghga-de/charts
          token: ${{ secrets.GITOPS_PAT }}
          ref: ${{ github.head_ref }}

      - uses: helmfile/helmfile-action@v1.0.0
        with:
          helmfile-version: 'v0.153.1'
          helm-version: 'v3.12.0'
          helm-plugins: >
            https://github.com/databus23/helm-diff
          helmfile-args: template --environment dev --file apps/data-portal --output-dir-template /tmp/gitops/GHGAinfra/data-portal

      - name: Commit changes to gitops/
        run: |
          git fetch
          git switch gitops
          rm -rf ./gitops
          mv /tmp/gitops .
          # Check for changes
          if [[ -n $(git status -s | grep "gitops/") ]]; then
            echo "There are changes to commit."

            # Set up Git user
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

            # Add all changes
            git add ./gitops

            # Commit changes
            git commit -m "Apply automatic changes"
            git push -f
            echo "Changes committed."
          else
            echo "No changes to commit."
          fi
