name: Update, Lint and Test Charts
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  update-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set variables
        id: vars
        run: |
          set -x
          chart_dirs=$(git --no-pager diff --name-only --diff-filter=M | grep Chart.yaml | grep -v "jobs" | sed 's|^./||' | cut -d'/' -f1 | sort | uniq | tr '\n' ',' | sed 's/,$//')
          echo "Processing charts in directories: $chart_dirs"
          echo "CHART_DIRS=$chart_dirs" >> $GITHUB_ENV
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip install semver ruamel.yaml requests
      - name: Add charts' dependency repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add ghga https://ghga-de.github.io/charts
      - name: Bump Chart version and update dependencies
        run: |
          for chart_dir in ${CHART_DIRS//,/ }; do
            python ./scripts/bump_charts.py --chart-dir $chart_dir
          done
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1   
      - name: Set chart directories
        id: chart-dirs
        run: |
          changed=$(ct list-changed --chart-dirs $CHART_DIRS --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            ct lint --chart-dirs $CHART_DIRS --target-branch ${{ github.event.repository.default_branch }} --validate-maintainers=false
          fi
      - name: Update branch
        uses: stefanzweifel/git-auto-commit-action@v5
        if: |
          github.event_name == 'pull_request' && 
          contains(github.event.pull_request.labels.*.name, 'updated charts')
        with:
          commit_message: "Apply automatic changes"