name: Update, Lint and Test Charts
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  update-charts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        chart-dirs:
          - archive/
          - base/ghga-common
          - utils/
    steps:
      - name: Set variables
        id: vars
        shell: bash
        run: |
          echo "CHART_DIRS=${{ matrix.chart-dirs }}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip install semver ruamel.yaml requests
      - name: Add charts' dependency repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add ghga https://ghga-de.github.io/charts
      - name: Bump Chart version and update dependencies for ${{ matrix.chart-dirs }}
        run: |
          python ./scripts/bump_charts.py --chart-dir ${{ matrix.chart-dirs }}
      - name: Bump Chart version and update dependencies
        run: |
          find ${{ matrix.chart-dirs }} -name "Chart.yaml" -exec dirname {} \; | xargs -I {} helm dep up {} --skip-refresh

  lint-test:
    needs: update-charts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart-dirs:
          - archive/
          - base/ghga-common
          - utils/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1   
      - name: Set chart directories
        id: chart-dirs
        run: |
          chart_dirs=$(find ${{ matrix.chart-dirs }} -name "Chart.yaml" -exec dirname {} \; | xargs dirname | sort | uniq |tr '\n' ',' | sed 's/,$//')
          echo "CHART_DIRS=$chart_dirs" >> $GITHUB_ENV
      - name: Add charts' dependency repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add ghga https://ghga-de.github.io/charts
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --chart-dirs ${{ env.CHART_DIRS }} --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "CHANGED=true" >> $GITHUB_OUTPUT
          fi
      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.CHANGED == 'true'
        run: |
          ct lint --chart-dirs ${{ env.CHART_DIRS }} --target-branch ${{ github.event.repository.default_branch }} --validate-maintainers=false

  update-branch:
    if: |
      github.event_name == 'pull_request' && 
      contains(github.event.pull_request.labels.*.name, 'updated charts')
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      if: |
        github.event_name == 'pull_request' && 
        contains(github.event.pull_request.labels.*.name, 'updated charts')
      with:
        commit_message: "Apply automatic changes"
