name: helmfile-template
on:
  push:
    branches:
      - main

jobs:
  template-dev:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: helmfile/helmfile-action@v1.0.0
        with:
          helmfile-version: 'v0.153.1'
          helm-version: 'v3.12.0'
          helm-plugins: >
            https://github.com/databus23/helm-diff
          helmfile-args: template --environment dev --file apps/data-portal --output-dir-template ${{ github.workspace }}/gitops/GHGAinfra/data-portal

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: .
          branch: gitops
          file_pattern: 'gitops/'
