name: Update, Lint and Test Charts
on: pull_request


jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        id: vars
        shell: bash
        run: |
          echo "CHART_DIRS=charts,charts/file-services-backend" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Add charts' dependency repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add ghga https://ghga-de.github.io/charts

      - name: Helm Build Dependencies
        run: |
          helm dependency build ./charts/ghga-common

      - name: Bump Chart version and update dependencies
        run: |
          for chart_dir in $CHART_DIRS; do
            python ./scripts/bump_charts.py
          done
      
      - name: Bump Chart version and update dependencies
        run: |
          for chart_dir in $CHART_DIRS; do
            helm dependency up $chart_dir --skip-refresh
          done
       
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --chart-dirs $CHART_DIRS --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --chart-dirs $CHART_DIRS --target-branch ${{ github.event.repository.default_branch }} --validate-maintainers=false

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Apply automatic changes"
