name: Library Release Workflow
on:
  release:
    types:
      - published
  workflow_run:
    workflows: [Release Charts]
    types:
      - completed
  workflow_dispatch:

jobs:
  update-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0
      
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install dependencies for scripts
        shell: bash
        run: pip install semver ruamel.yaml requests
      
      - name: Add charts' dependency repositories
        shell: bash
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add ghga https://ghga-de.github.io/charts
     
      # Note: it is not easily possible to pass the version of ghga-common as an input to this workflow.
      #       Therefore, we retrieve the most recent release tag of ghga-common and use it to bump the chart versions.
      - name: Get most recent release tag
        shell: bash
        run: |
          ghga_common=$(curl -s "https://api.github.com/repos/ghga-de/charts/releases?per_page=300" | jq -r 'map(select(.tag_name | startswith("ghga-common"))) | sort_by(.published_at) | reverse | .[0] | .tag_name')
          ghga_common_version=${ghga_common#ghga-common-}
          echo "Processing charts in directories: archive/ with library version $ghga_common_version"
          echo "GHGA_COMMON_VERSION=$ghga_common_version" >> $GITHUB_ENV

      - name: Bump Chart version and update dependencies
        shell: bash
        run: |
          python ./scripts/bump_charts.py --chart-dir archive/ --library-chart-version $GHGA_COMMON_VERSION

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: archive/
          labels: chart updates
          assignees: ckaipf
          reviewers: ckaipf
          title: Update archive charts to feature/bump-${{ env.GHGA_COMMON_VERSION }}
          commit-message: Update archive charts to feature/bump-${{ env.GHGA_COMMON_VERSION }}
          branch: feature/bump-${{ env.GHGA_COMMON_VERSION }}
          delete-branch: true
          base: main
