name: Lint test manifests with kubeconform

on:
  pull_request:
    types:
      - opened
      - synchronize
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint manifests with kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: "/kubeconform"
          args: >
            -summary 
            -output json 
            -ignore-missing-schemas 
            -schema-location default 
            -schema-location https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json 
            base/tests/rendered
